#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
统一错误码常量
与 Node 约定一致，供接口返回 body.error_code 及 last_error 写入
"""

# 服务与设备
PYTHON_SERVICE_UNAVAILABLE = "PYTHON_SERVICE_UNAVAILABLE"
AI_DEVICE_NOT_SUPPORTED = "AI_DEVICE_NOT_SUPPORTED"
AI_TIMEOUT = "AI_TIMEOUT"

# 输入
IMAGE_DECODE_FAILED = "IMAGE_DECODE_FAILED"
INVALID_REQUEST = "INVALID_REQUEST"

# 模型缺失（能力未加载或 profile 下关闭）
CAPTION_MODEL_MISSING = "CAPTION_MODEL_MISSING"
OBJECT_MODEL_MISSING = "OBJECT_MODEL_MISSING"
SCENE_MODEL_MISSING = "SCENE_MODEL_MISSING"
OCR_MODEL_MISSING = "OCR_MODEL_MISSING"
FACE_MODEL_MISSING = "FACE_MODEL_MISSING"
CLEANUP_MODEL_MISSING = "CLEANUP_MODEL_MISSING"
EMBEDDING_MODEL_MISSING = "EMBEDDING_MODEL_MISSING"

# 通用
AI_SERVICE_ERROR = "AI_SERVICE_ERROR"
