/*
 * @Author: zhangshouchang
 * @Date: 2024-12-30 23:42:12
 * @LastEditors: zhangshouchang
 * @LastEditTime: 2025-08-14 01:01:38
 * @Description: File description
 */
module.exports = {
  // 成功码
  SUCCESS_CODES: {
    REQUEST_COMPLETED: 'REQUEST_COMPLETED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    ACCOUNT_VERIFIED_SUCCESS: 'ACCOUNT_VERIFIED_SUCCESS',
    EMAIL_VERIFICATION_RESENT: 'EMAIL_VERIFICATION_RESENT',
    ACCOUNT_PENDING_ACTIVATION: 'ACCOUNT_PENDING_ACTIVATION',
    PASSWORD_RESET_EMAIL_SENT: 'PASSWORD_RESET_EMAIL_SENT',
    PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
    FILE_UPLOADED_SUCCESSFULLY: 'FILE_UPLOADED_SUCCESSFULLY'
  },

  // 错误码
  ERROR_CODES: {
    NO_UPLOAD_FILE: 'NO_UPLOAD_FILE',
    SEND_ACTIVATION_EMAIL_FAILED: 'SEND_ACTIVATION_EMAIL_FAILED',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    UNAUTHORIZED: 'UNAUTHORIZED',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INVALID_JWT_TOKEN: 'INVALID_JWT_TOKEN',
    EMAIL_REQUIRED: 'EMAIL_REQUIRED',
    PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
    INVALID_PARAMETERS: 'INVALID_PARAMETERS',
    ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
    ACCOUNT_ALREADY_ACTIVE: 'ACCOUNT_ALREADY_ACTIVE',
    ACCOUNT_CANNOT_BE_VERIFIED: 'ACCOUNT_CANNOT_BE_VERIFIED',
    ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
    VERIFICATION_TOKEN_REQUIRED: 'VERIFICATION_TOKEN_REQUIRED',
    VERIFICATION_TOKEN_INVALID: 'VERIFICATION_TOKEN_INVALID',
    RESET_TOKEN_INVALID_OR_EXPIRED: 'RESET_TOKEN_INVALID_OR_EXPIRED',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    REQUESTS_TOO_FREQUENT: 'REQUESTS_TOO_FREQUENT',
    SERVER_ERROR: 'SERVER_ERROR',
    SEND_MAIL_ERROR: 'SEND_MAIL_ERROR',
    DATA_INSERT_FAILED: 'DATA_INSERT_FAILED',
    FAILED_SELECT_GROUPS_BY_YEAR: 'FAILED_SELECT_GROUPS_BY_YEAR',
    FAILED_SELECT_GROUPS_BY_MONTH: 'FAILED_SELECT_GROUPS_BY_MONTH',
    INVALID_EMAIL_FORMAT: 'INVALID_EMAIL_FORMAT',
    UPLOAD_SESSION_NOT_FOUND: 'UPLOAD_SESSION_NOT_FOUND',
    PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    UNSUPPORTED_OPERATION: 'UNSUPPORTED_OPERATION',
    UPDATE_VERIFICATION_TOKEN_ERROR: 'UPDATE_VERIFICATION_TOKEN_ERROR',
    COMPARE_PASSWORD_ERROR: 'COMPARE_PASSWORD_ERROR',
    NETWORK_TIMEOUT: 'NETWORK_TIMEOUT',
    BAD_GATEWAY: 'BAD_GATEWAY',
    FILE_NOT_FOUND: 'FILE_NOT_FOUND',
    DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
    DUPLICATE_PERSON_NAME: 'DUPLICATE_PERSON_NAME',
    DATA_UPDATE_FAILED: 'DATA_UPDATE_FAILED',
    DATA_DELETE_FAILED: 'DATA_DELETE_FAILED',
    PERSON_COVER_FACE_THUMBNAIL_UNAVAILABLE: 'PERSON_COVER_FACE_THUMBNAIL_UNAVAILABLE',
    EXPORT_BATCH_LIMIT_EXCEEDED: 'EXPORT_BATCH_LIMIT_EXCEEDED'
  }
}
