/*
 * @Author: zhangshouchang
 * @Date: 2024-12-30 23:42:12
 * @LastEditors: zhangshouchang
 * @LastEditTime: 2024-12-31 16:52:28
 * @Description: File description
 */

module.exports = {
  EMAIL_REQUIRED: "EMAIL_REQUIRED",
  PASSWORD_REQUIRED: "PASSWORD_REQUIRED",
  INVALID_PARAMETERS: "INVALID_PARAMETERS",
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  ACCOUNT_ALREADY_ACTIVE: "ACCOUNT_ALREADY_ACTIVE",
  ACCOUNT_CANNOT_BE_VERIFIED: "ACCOUNT_CANNOT_BE_VERIFIED",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  ACCOUNT_PENDING_ACTIVATION: "ACCOUNT_PENDING_ACTIVATION",
  EMAIL_VERIFICATION_RESENT: "EMAIL_VERIFICATION_RESENT",
  VERIFICATION_TOKEN_REQUIRED: "VERIFICATION_TOKEN_REQUIRED",
  VERIFICATION_TOKEN_INVALID: "VERIFICATION_TOKEN_INVALID",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  REQUESTS_TOO_FREQUENT: "REQUESTS_TOO_FREQUENT",
  SERVER_ERROR: "SERVER_ERROR",
  ACCOUNT_VERIFIED_SUCCESS: "ACCOUNT_VERIFIED_SUCCESS",
  REDIS_ERROR: "REDIS_ERROR",
  SEND_MAIL_ERROR: "SEND_MAIL_ERROR",
  FAILED_TO_READ_FILE: "FAILED_TO_READ_FILE",
  TABLE_CREATE_FAILED: "TABLE_CREATE_FAILED",
  DATA_INSERT_FAILED: "DATA_INSERT_FAILED",
  FAILED_SELECT_ALL_DATA: "FAILED_SELECT_ALL_DATA",
  FAILED_SELECT_BY_PAGE: "FAILED_SELECT_BY_PAGE",
  FAILED_SELECT_BY_TIME_RANGE: "FAILED_SELECT_BY_TIME_RANGE",
  FAILED_SELECT_GROUPS_BY_YEAR: "FAILED_SELECT_GROUPS_BY_YEAR",
  FAILED_SELECT_GROUPS_BY_MONTH: "FAILED_SELECT_GROUPS_BY_MONTH",
  INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
  PASSWORD_TOO_WEAK: "PASSWORD_TOO_WEAK",
  INVALID_IMAGE_DATA: "INVALID_IMAGE_DATA",
  UPDATE_VERIFICATION_TOKEN_ERROR: "UPDATE_VERIFICATION_TOKEN_ERROR",
  SET_REDIS_KEY_ERROR: "SET_REDIS_KEY_ERROR",
  REDIS_SERVER_ERROR: "REDIS_SERVER_ERROR",
  COMPARE_PASSWORD_ERROR: "COMPARE_PASSWORD_ERROR",
};
